### ISSUE TITLE
Overflow whn loading map.json

### ISSUE THREAD

**Issue by arnaudlorin** [arthurBricq/crafty#6]
When loading map.json, get the following message:

`thread 'main' has overflowed its stack`

The file is probably too big, a new format to save the map should be develop

**Comment by arthurBricq** [comment]
It seems that for now, this is solved by https://github.com/arthurBricq/crafty/commit/a7f25e3b71983470d391eb98acba3a7a284ee5ec

I have decreased the file size of roughly 10 times.

Let's see how it scales in the future, but for now I close the issue.
